using System.Runtime.Serialization;

namespace Trading212.API.DTOs.Enums
{
    public enum DividendType
    {
        [EnumMember(Value = "ORDINARY")]
        ORDINARY,

        [EnumMember(Value = "BONUS")]
        BONUS,

        [EnumMember(Value = "PROPERTY_INCOME")]
        PROPERTY_INCOME,

        [EnumMember(Value = "RETURN_OF_CAPITAL_NON_US")]
        RETURN_OF_CAPITAL_NON_US,

        [EnumMember(Value = "DEMERGER")]
        DEMERGER,

        [EnumMember(Value = "INTEREST")]
        INTEREST,

        [EnumMember(Value = "CAPITAL_GAINS_DISTRIBUTION_NON_US")]
        CAPITAL_GAINS_DISTRIBUTION_NON_US,

        [EnumMember(Value = "INTERIM_LIQUIDATION")]
        INTERIM_LIQUIDATION,

        [EnumMember(Value = "ORDINARY_MANUFACTURED_PAYMENT")]
        ORDINARY_MANUFACTURED_PAYMENT,

        [EnumMember(Value = "BONUS_MANUFACTURED_PAYMENT")]
        BONUS_MANUFACTURED_PAYMENT,

        [EnumMember(Value = "PROPERTY_INCOME_MANUFACTURED_PAYMENT")]
        PROPERTY_INCOME_MANUFACTURED_PAYMENT,

        [EnumMember(Value = "RETURN_OF_CAPITAL_NON_US_MANUFACTURED_PAYMENT")]
        RETURN_OF_CAPITAL_NON_US_MANUFACTURED_PAYMENT,

        [EnumMember(Value = "DEMERGER_MANUFACTURED_PAYMENT")]
        DEMERGER_MANUFACTURED_PAYMENT,

        [EnumMember(Value = "INTEREST_MANUFACTURED_PAYMENT")]
        INTEREST_MANUFACTURED_PAYMENT,

        [EnumMember(Value = "CAPITAL_GAINS_DISTRIBUTION_NON_US_MANUFACTURED_PAYMENT")]
        CAPITAL_GAINS_DISTRIBUTION_NON_US_MANUFACTURED_PAYMENT,

        [EnumMember(Value = "INTERIM_LIQUIDATION_MANUFACTURED_PAYMENT")]
        INTERIM_LIQUIDATION_MANUFACTURED_PAYMENT,

        [EnumMember(Value = "INTEREST_PAID_BY_US_OBLIGORS")]
        INTEREST_PAID_BY_US_OBLIGORS,

        [EnumMember(Value = "INTEREST_PAID_BY_FOREIGN_CORPORATIONS")]
        INTEREST_PAID_BY_FOREIGN_CORPORATIONS,

        [EnumMember(Value = "DIVIDENDS_PAID_BY_US_CORPORATIONS")]
        DIVIDENDS_PAID_BY_US_CORPORATIONS,

        [EnumMember(Value = "DIVIDENDS_PAID_BY_FOREIGN_CORPORATIONS")]
        DIVIDENDS_PAID_BY_FOREIGN_CORPORATIONS,

        [EnumMember(Value = "CAPITAL_GAINS")]
        CAPITAL_GAINS,

        [EnumMember(Value = "REAL_PROPERTY_INCOME_AND_NATURAL_RESOURCES_ROYALTIES")]
        REAL_PROPERTY_INCOME_AND_NATURAL_RESOURCES_ROYALTIES,

        [EnumMember(Value = "OTHER_INCOME")]
        OTHER_INCOME,

        [EnumMember(Value = "QUALIFIED_INVESTMENT_ENTITY")]
        QUALIFIED_INVESTMENT_ENTITY,

        [EnumMember(Value = "TRUST_DISTRIBUTION")]
        TRUST_DISTRIBUTION,

        [EnumMember(Value = "PUBLICLY_TRADED_PARTNERSHIP_DISTRIBUTION")]
        PUBLICLY_TRADED_PARTNERSHIP_DISTRIBUTION,

        [EnumMember(Value = "CAPITAL_GAINS_DISTRIBUTION")]
        CAPITAL_GAINS_DISTRIBUTION,

        [EnumMember(Value = "RETURN_OF_CAPITAL")]
        RETURN_OF_CAPITAL,

        [EnumMember(Value = "OTHER_DIVIDEND_EQUIVALENT")]
        OTHER_DIVIDEND_EQUIVALENT,

        [EnumMember(Value = "TAX_EVENT_1446F_FOR_PUBLICLY_TRADED_SECURITIES")]
        TAX_EVENT_1446F_FOR_PUBLICLY_TRADED_SECURITIES,

        [EnumMember(Value = "PTP_UNCHARACTERISED_INCOME")]
        PTP_UNCHARACTERISED_INCOME,

        [EnumMember(Value = "MULTIPLE_1042S_TAX_COMPONENTS")]
        MULTIPLE_1042S_TAX_COMPONENTS,

        [EnumMember(Value = "INTEREST_PAID_BY_US_OBLIGORS_MANUFACTURED_PAYMENT")]
        INTEREST_PAID_BY_US_OBLIGORS_MANUFACTURED_PAYMENT,

        [EnumMember(Value = "INTEREST_PAID_BY_FOREIGN_CORPORATIONS_MANUFACTURED_PAYMENT")]
        INTEREST_PAID_BY_FOREIGN_CORPORATIONS_MANUFACTURED_PAYMENT,

        [EnumMember(Value = "DIVIDENDS_PAID_BY_US_CORPORATIONS_MANUFACTURED_PAYMENT")]
        DIVIDENDS_PAID_BY_US_CORPORATIONS_MANUFACTURED_PAYMENT,

        [EnumMember(Value = "DIVIDENDS_PAID_BY_FOREIGN_CORPORATIONS_MANUFACTURED_PAYMENT")]
        DIVIDENDS_PAID_BY_FOREIGN_CORPORATIONS_MANUFACTURED_PAYMENT,

        [EnumMember(Value = "CAPITAL_GAINS_MANUFACTURED_PAYMENT")]
        CAPITAL_GAINS_MANUFACTURED_PAYMENT,

        [EnumMember(Value = "REAL_PROPERTY_INCOME_AND_NATURAL_RESOURCES_ROYALTIES_MANUFACTURED_PAYMENT")]
        REAL_PROPERTY_INCOME_AND_NATURAL_RESOURCES_ROYALTIES_MANUFACTURED_PAYMENT,

        [EnumMember(Value = "OTHER_INCOME_MANUFACTURED_PAYMENT")]
        OTHER_INCOME_MANUFACTURED_PAYMENT,

        [EnumMember(Value = "QUALIFIED_INVESTMENT_ENTITY_MANUFACTURED_PAYMENT")]
        QUALIFIED_INVESTMENT_ENTITY_MANUFACTURED_PAYMENT,

        [EnumMember(Value = "TRUST_DISTRIBUTION_MANUFACTURED_PAYMENT")]
        TRUST_DISTRIBUTION_MANUFACTURED_PAYMENT,

        [EnumMember(Value = "PUBLICLY_TRADED_PARTNERSHIP_DISTRIBUTION_MANUFACTURED_PAYMENT")]
        PUBLICLY_TRADED_PARTNERSHIP_DISTRIBUTION_MANUFACTURED_PAYMENT,

        [EnumMember(Value = "CAPITAL_GAINS_DISTRIBUTION_MANUFACTURED_PAYMENT")]
        CAPITAL_GAINS_DISTRIBUTION_MANUFACTURED_PAYMENT,

        [EnumMember(Value = "RETURN_OF_CAPITAL_MANUFACTURED_PAYMENT")]
        RETURN_OF_CAPITAL_MANUFACTURED_PAYMENT,

        [EnumMember(Value = "OTHER_DIVIDEND_EQUIVALENT_MANUFACTURED_PAYMENT")]
        OTHER_DIVIDEND_EQUIVALENT_MANUFACTURED_PAYMENT,

        [EnumMember(Value = "TAX_EVENT_1446F_FOR_PUBLICLY_TRADED_SECURITIES_MANUFACTURED_PAYMENT")]
        TAX_EVENT_1446F_FOR_PUBLICLY_TRADED_SECURITIES_MANUFACTURED_PAYMENT,

        [EnumMember(Value = "PTP_UNCHARACTERISED_INCOME_MANUFACTURED_PAYMENT")]
        PTP_UNCHARACTERISED_INCOME_MANUFACTURED_PAYMENT,

        [EnumMember(Value = "MULTIPLE_1042S_TAX_COMPONENTS_MANUFACTURED_PAYMENT")]
        MULTIPLE_1042S_TAX_COMPONENTS_MANUFACTURED_PAYMENT
    }
}
